use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LanguagePack {
    pub code: String,
    pub name: String,
    pub native_name: String,
    pub rtl: bool,
    pub strings: HashMap<String, String>,
}

pub const DEFAULT_LANGUAGES: &[(&str, &str, &str, bool)] = &[
    ("en", "English", "English", false),
    ("en-US", "English (US)", "English (US)", false),
    ("en-GB", "English (UK)", "English (UK)", false),
    ("en-CA", "English (Canada)", "English (Canada)", false),
    ("en-AU", "English (Australia)", "English (Australia)", false),
    ("en-IN", "English (India)", "English (India)", false),
    ("en-NG", "English (Nigeria)", "English (Nigeria)", false),
    ("en-KE", "English (Kenya)", "English (Kenya)", false),
    (
        "en-ZA",
        "English (South Africa)",
        "English (South Africa)",
        false,
    ),
    ("ar", "Arabic", "العربية", true),
    ("ar-SA", "Arabic (Saudi)", "العربية السعودية", true),
    ("ar-EG", "Arabic (Egypt)", "العربية المصرية", true),
    ("ar-UAE", "Arabic (UAE)", "العربية الإماراتية", true),
    ("ar-MA", "Arabic (Morocco)", "العربية المغربية", true),
    ("ar-DZ", "Arabic (Algeria)", "العربية الجزائرية", true),
    ("ar-TN", "Arabic (Tunisia)", "العربية التونسية", true),
    ("ar-IQ", "Arabic (Iraq)", "العربية العراقية", true),
    ("ar-SY", "Arabic (Syria)", "العربية السورية", true),
    ("ar-JO", "Arabic (Jordan)", "العربية الأردنية", true),
    ("ar-LB", "Arabic (Lebanon)", "العربية اللبنانية", true),
    ("ar-YE", "Arabic (Yemen)", "العربية اليمنية", true),
    ("es", "Spanish", "Español", false),
    ("es-ES", "Spanish (Spain)", "Español (España)", false),
    ("es-MX", "Spanish (Mexico)", "Español (México)", false),
    ("es-AR", "Spanish (Argentina)", "Español (Argentina)", false),
    ("es-CO", "Spanish (Colombia)", "Español (Colombia)", false),
    ("es-CL", "Spanish (Chile)", "Español (Chile)", false),
    ("es-PE", "Spanish (Peru)", "Español (Perú)", false),
    ("es-VE", "Spanish (Venezuela)", "Español (Venezuela)", false),
    ("es-BR", "Spanish (Brazil)", "Español (Brasil)", false),
    ("es-PY", "Spanish (Paraguay)", "Español (Paraguay)", false),
    ("es-UY", "Spanish (Uruguay)", "Español (Uruguay)", false),
    ("es-BO", "Spanish (Bolivia)", "Español (Bolivia)", false),
    ("es-EC", "Spanish (Ecuador)", "Español (Ecuador)", false),
    (
        "es-CR",
        "Spanish (Costa Rica)",
        "Español (Costa Rica)",
        false,
    ),
    ("es-PA", "Spanish (Panama)", "Español (Panamá)", false),
    ("es-DO", "Spanish (Dominican)", "Español (Rep. Dom.)", false),
    ("es-GT", "Spanish (Guatemala)", "Español (Guatemala)", false),
    ("es-HN", "Spanish (Honduras)", "Español (Honduras)", false),
    ("es-NI", "Spanish (Nicaragua)", "Español (Nicaragua)", false),
    (
        "es-SV",
        "Spanish (El Salvador)",
        "Español (El Salvador)",
        false,
    ),
    ("fr", "French", "Français", false),
    ("fr-FR", "French (France)", "Français (France)", false),
    ("fr-CA", "French (Canada)", "Français (Canada)", false),
    ("fr-BE", "French (Belgium)", "Français (Belgique)", false),
    ("fr-CH", "French (Switzerland)", "Français (Suisse)", false),
    (
        "fr-LU",
        "French (Luxembourg)",
        "Français (Luxembourg)",
        false,
    ),
    ("fr-MA", "French (Morocco)", "Français (Maroc)", false),
    ("fr-DZ", "French (Algeria)", "Français (Algérie)", false),
    ("fr-TN", "French (Tunisia)", "Français (Tunisie)", false),
    ("fr-CM", "French (Cameroon)", "Français (Cameroun)", false),
    (
        "fr-CI",
        "French (Côte d'Ivoire)",
        "Français (Côte d'Ivoire)",
        false,
    ),
    ("fr-SN", "French (Senegal)", "Français (Sénégal)", false),
    ("fr-CD", "French (Congo DR)", "Français (RDC)", false),
    ("fr-RW", "French (Rwanda)", "Français (Rwanda)", false),
    (
        "fr-BF",
        "French (Burkina Faso)",
        "Français (Burkina Faso)",
        false,
    ),
    ("fr-ML", "French (Mali)", "Français (Mali)", false),
    ("fr-GN", "French (Guinea)", "Français (Guinée)", false),
    ("fr-TD", "French (Chad)", "Français (Tchad)", false),
    ("fr-HT", "French (Haiti)", "Français (Haïti)", false),
    ("fr-LB", "French (Lebanon)", "Français (Liban)", false),
    ("ru", "Russian", "Русский", false),
    ("ru-RU", "Russian (Russia)", "Русский (Россия)", false),
    ("ru-UA", "Russian (Ukraine)", "Русский (Украина)", false),
    (
        "ru-KZ",
        "Russian (Kazakhstan)",
        "Русский (Казахстан)",
        false,
    ),
    ("ru-BY", "Russian (Belarus)", "Русский (Беларусь)", false),
    (
        "ru-UZ",
        "Russian (Uzbekistan)",
        "Русский (Узбекистан)",
        false,
    ),
    ("ru-KG", "Russian (Kyrgyzstan)", "Русский (Киргизия)", false),
    (
        "ru-TJ",
        "Russian (Tajikistan)",
        "Русский (Таджикистан)",
        false,
    ),
    (
        "ru-TM",
        "Russian (Turkmenistan)",
        "Русский (Туркменистан)",
        false,
    ),
    ("ru-MD", "Russian (Moldova)", "Русский (Молдова)", false),
    ("zh", "Chinese", "中文", false),
    ("zh-CN", "Chinese (Simplified)", "简体中文", false),
    ("zh-TW", "Chinese (Traditional)", "繁體中文", false),
    ("zh-HK", "Chinese (Hong Kong)", "香港中文", false),
    ("zh-MO", "Chinese (Macau)", "澳門中文", false),
    ("zh-SG", "Chinese (Singapore)", "新加坡中文", false),
    ("hi", "Hindi", "हिन्दी", false),
    ("hi-IN", "Hindi (India)", "हिन्दी (भारत)", false),
    ("bn", "Bengali", "বাংলা", false),
    ("bn-BD", "Bengali (Bangladesh)", "বাংলা (বাংলাদেশ)", false),
    ("bn-IN", "Bengali (India)", "বাংলা (ভারত)", false),
    ("pt", "Portuguese", "Português", false),
    (
        "pt-PT",
        "Portuguese (Portugal)",
        "Português (Portugal)",
        false,
    ),
    ("pt-BR", "Portuguese (Brazil)", "Português (Brasil)", false),
    ("pt-AO", "Portuguese (Angola)", "Português (Angola)", false),
    (
        "pt-MZ",
        "Portuguese (Mozambique)",
        "Português (Moçambique)",
        false,
    ),
    (
        "pt-GW",
        "Portuguese (Guinea-Bissau)",
        "Português (Guiné-Bissau)",
        false,
    ),
    (
        "pt-CV",
        "Portuguese (Cape Verde)",
        "Português (Cabo Verde)",
        false,
    ),
    ("ja", "Japanese", "日本語", false),
    ("ja-JP", "Japanese (Japan)", "日本語 (日本)", false),
    ("de", "German", "Deutsch", false),
    ("de-DE", "German (Germany)", "Deutsch (Deutschland)", false),
    ("de-AT", "German (Austria)", "Deutsch (Österreich)", false),
    ("de-CH", "German (Switzerland)", "Deutsch (Schweiz)", false),
    ("de-BE", "German (Belgium)", "Deutsch (Belgien)", false),
    ("de-LU", "German (Luxembourg)", "Deutsch (Luxemburg)", false),
    ("it", "Italian", "Italiano", false),
    ("it-IT", "Italian (Italy)", "Italiano (Italia)", false),
    (
        "it-CH",
        "Italian (Switzerland)",
        "Italiano (Svizzera)",
        false,
    ),
    ("ko", "Korean", "한국어", false),
    ("ko-KR", "Korean (South Korea)", "한국어 (대한민국)", false),
    ("ko-KP", "Korean (North Korea)", "한국어 (조선)", false),
    ("nl", "Dutch", "Nederlands", false),
    (
        "nl-NL",
        "Dutch (Netherlands)",
        "Nederlands (Nederland)",
        false,
    ),
    ("nl-BE", "Dutch (Belgium)", "Nederlands (België)", false),
    ("tr", "Turkish", "Türkçe", false),
    ("tr-TR", "Turkish (Turkey)", "Türkçe (Türkiye)", false),
    ("tr-CY", "Turkish (Cyprus)", "Türkçe (Kıbrıs)", false),
    ("vi", "Vietnamese", "Tiếng Việt", false),
    (
        "vi-VN",
        "Vietnamese (Vietnam)",
        "Tiếng Việt (Việt Nam)",
        false,
    ),
    ("th", "Thai", "ไทย", false),
    ("th-TH", "Thai (Thailand)", "ไทย (ประเทศไทย)", false),
    ("id", "Indonesian", "Bahasa Indonesia", false),
    (
        "id-ID",
        "Indonesian (Indonesia)",
        "Bahasa Indonesia (Indonesia)",
        false,
    ),
    ("ms", "Malay", "Bahasa Melayu", false),
    (
        "ms-MY",
        "Malay (Malaysia)",
        "Bahasa Melayu (Malaysia)",
        false,
    ),
    ("ms-BN", "Malay (Brunei)", "Bahasa Melayu (Brunei)", false),
    (
        "ms-SG",
        "Malay (Singapore)",
        "Bahasa Melayu (Singapura)",
        false,
    ),
    ("tl", "Filipino", "Filipino", false),
    (
        "tl-PH",
        "Filipino (Philippines)",
        "Filipino (Pilipinas)",
        false,
    ),
    ("ur", "Urdu", "اردو", true),
    ("ur-PK", "Urdu (Pakistan)", "اردو (پاکستان)", true),
    ("ur-IN", "Urdu (India)", "اردو (بھارت)", true),
    ("fa", "Persian", "فارسی", true),
    ("fa-IR", "Persian (Iran)", "فارسی (ایران)", true),
    ("fa-AF", "Persian (Afghanistan)", "فارسی (افغانستان)", true),
    ("he", "Hebrew", "עברית", true),
    ("he-IL", "Hebrew (Israel)", "עברית (ישראל)", true),
    ("uk", "Ukrainian", "Українська", false),
    (
        "uk-UA",
        "Ukrainian (Ukraine)",
        "Українська (Україна)",
        false,
    ),
    ("pl", "Polish", "Polski", false),
    ("pl-PL", "Polish (Poland)", "Polski (Polska)", false),
    ("ro", "Romanian", "Română", false),
    ("ro-RO", "Romanian (Romania)", "Română (România)", false),
    ("ro-MD", "Romanian (Moldova)", "Română (Moldova)", false),
    ("cs", "Czech", "Čeština", false),
    ("cs-CZ", "Czech (Czechia)", "Čeština (Česko)", false),
    ("sk", "Slovak", "Slovenčina", false),
    (
        "sk-SK",
        "Slovak (Slovakia)",
        "Slovenčina (Slovensko)",
        false,
    ),
    ("hu", "Hungarian", "Magyar", false),
    (
        "hu-HU",
        "Hungarian (Hungary)",
        "Magyar (Magyarország)",
        false,
    ),
    ("el", "Greek", "Ελληνικά", false),
    ("el-GR", "Greek (Greece)", "Ελληνικά (Ελλάδα)", false),
    ("el-CY", "Greek (Cyprus)", "Ελληνικά (Κύπρος)", false),
    ("sv", "Swedish", "Svenska", false),
    ("sv-SE", "Swedish (Sweden)", "Svenska (Sverige)", false),
    ("sv-FI", "Swedish (Finland)", "Svenska (Finland)", false),
    ("da", "Danish", "Dansk", false),
    ("da-DK", "Danish (Denmark)", "Dansk (Danmark)", false),
    ("no", "Norwegian", "Norsk", false),
    ("no-NO", "Norwegian (Norway)", "Norsk (Norge)", false),
    ("fi", "Finnish", "Suomi", false),
    ("fi-FI", "Finnish (Finland)", "Suomi (Suomi)", false),
    ("is", "Icelandic", "Íslenska", false),
    ("is-IS", "Icelandic (Iceland)", "Íslenska (Ísland)", false),
    ("et", "Estonian", "Eesti", false),
    ("et-EE", "Estonian (Estonia)", "Eesti (Eesti)", false),
    ("lv", "Latvian", "Latviešu", false),
    ("lv-LV", "Latvian (Latvia)", "Latviešu (Latvija)", false),
    ("lt", "Lithuanian", "Lietuvių", false),
    (
        "lt-LT",
        "Lithuanian (Lithuania)",
        "Lietuvių (Lietuva)",
        false,
    ),
    ("bg", "Bulgarian", "Български", false),
    (
        "bg-BG",
        "Bulgarian (Bulgaria)",
        "Български (България)",
        false,
    ),
    ("sr", "Serbian", "Српски", false),
    ("sr-RS", "Serbian (Serbia)", "Српски (Србија)", false),
    ("hr", "Croatian", "Hrvatski", false),
    ("hr-HR", "Croatian (Croatia)", "Hrvatski (Hrvatska)", false),
    ("sl", "Slovenian", "Slovenščina", false),
    (
        "sl-SI",
        "Slovenian (Slovenia)",
        "Slovenščina (Slovenija)",
        false,
    ),
    ("mk", "Macedonian", "Македонски", false),
    (
        "mk-MK",
        "Macedonian (N. Macedonia)",
        "Македонски (Северна Македонија)",
        false,
    ),
    ("sq", "Albanian", "Shqip", false),
    ("sq-AL", "Albanian (Albania)", "Shqip (Shqipëri)", false),
    ("sq-KS", "Albanian (Kosovo)", "Shqip (Kosovë)", false),
    ("bs", "Bosnian", "Bosanski", false),
    (
        "bs-BA",
        "Bosnian (Bosnia)",
        "Bosanski (Bosna i Hercegovina)",
        false,
    ),
    ("me", "Montenegrin", "Crnogorski", false),
    (
        "me-ME",
        "Montenegrin (Montenegro)",
        "Crnogorski (Crna Gora)",
        false,
    ),
    ("ca", "Catalan", "Català", false),
    ("ca-ES", "Catalan (Spain)", "Català (Espanya)", false),
    ("ca-AD", "Catalan (Andorra)", "Català (Andorra)", false),
    ("eu", "Basque", "Euskara", false),
    ("eu-ES", "Basque (Spain)", "Euskara (Espainia)", false),
    ("gl", "Galician", "Galego", false),
    ("gl-ES", "Galician (Spain)", "Galego (España)", false),
    ("ga", "Irish", "Gaeilge", false),
    ("ga-IE", "Irish (Ireland)", "Gaeilge (Éire)", false),
    ("cy", "Welsh", "Cymraeg", false),
    ("cy-GB", "Welsh (UK)", "Cymraeg (Cymru)", false),
    ("gd", "Scottish Gaelic", "Gàidhlig", false),
    (
        "gd-GB",
        "Scottish Gaelic (Scotland)",
        "Gàidhlig (Alba)",
        false,
    ),
    ("mt", "Maltese", "Malti", false),
    ("mt-MT", "Maltese (Malta)", "Malti (Malta)", false),
    ("sw", "Swahili", "Kiswahili", false),
    ("sw-KE", "Swahili (Kenya)", "Kiswahili (Kenya)", false),
    ("sw-TZ", "Swahili (Tanzania)", "Kiswahili (Tanzania)", false),
    ("sw-UG", "Swahili (Uganda)", "Kiswahili (Uganda)", false),
    ("sw-RW", "Swahili (Rwanda)", "Kiswahili (Rwanda)", false),
    ("sw-BI", "Swahili (Burundi)", "Kiswahili (Burundi)", false),
    ("sw-CD", "Swahili (Congo DR)", "Kiswahili (RDC)", false),
    ("am", "Amharic", "አማርኛ", false),
    ("am-ET", "Amharic (Ethiopia)", "አማርኛ (ኢትዮጵያ)", false),
    ("ha", "Hausa", "Hausa", false),
    ("ha-NG", "Hausa (Nigeria)", "Hausa (Nigeria)", false),
    ("ha-NE", "Hausa (Niger)", "Hausa (Nijar)", false),
    ("yo", "Yoruba", "Yorùbá", false),
    ("yo-NG", "Yoruba (Nigeria)", "Yorùbá (Nàìjíríà)", false),
    ("ig", "Igbo", "Igbo", false),
    ("ig-NG", "Igbo (Nigeria)", "Igbo (Nigeria)", false),
    ("rw", "Kinyarwanda", "Kinyarwanda", false),
    (
        "rw-RW",
        "Kinyarwanda (Rwanda)",
        "Kinyarwanda (Rwanda)",
        false,
    ),
    ("ln", "Lingala", "Lingála", false),
    ("ln-CD", "Lingala (Congo DR)", "Lingála (RDC)", false),
    ("ln-CG", "Lingala (Congo)", "Lingála (Kongo)", false),
    ("ny", "Chichewa", "Chichewa", false),
    ("ny-MW", "Chichewa (Malawi)", "Chichewa (Malawi)", false),
    ("st", "Sesotho", "Sesotho", false),
    ("st-LS", "Sesotho (Lesotho)", "Sesotho (Lesotho)", false),
    (
        "st-ZA",
        "Sesotho (South Africa)",
        "Sesotho (Afrika Borwa)",
        false,
    ),
    ("tn", "Setswana", "Setswana", false),
    ("tn-BW", "Setswana (Botswana)", "Setswana (Botswana)", false),
    (
        "tn-ZA",
        "Setswana (South Africa)",
        "Setswana (Aforika Borwa)",
        false,
    ),
    ("xh", "Xhosa", "isiXhosa", false),
    (
        "xh-ZA",
        "Xhosa (South Africa)",
        "isiXhosa (eMzantsi Afrika)",
        false,
    ),
    ("zu", "Zulu", "isiZulu", false),
    (
        "zu-ZA",
        "Zulu (South Africa)",
        "isiZulu (eNingizimu Afrika)",
        false,
    ),
    ("af", "Afrikaans", "Afrikaans", false),
    (
        "af-ZA",
        "Afrikaans (South Africa)",
        "Afrikaans (Suid-Afrika)",
        false,
    ),
    ("af-NA", "Afrikaans (Namibia)", "Afrikaans (Namibië)", false),
    ("mg", "Malagasy", "Malagasy", false),
    (
        "mg-MG",
        "Malagasy (Madagascar)",
        "Malagasy (Madagasikara)",
        false,
    ),
    ("si", "Sinhala", "සිංහල", false),
    ("si-LK", "Sinhala (Sri Lanka)", "සිංහල (ශ්‍රී ලංකාව)", false),
    ("ta", "Tamil", "தமிழ்", false),
    ("ta-IN", "Tamil (India)", "தமிழ் (இந்தியா)", false),
    ("ta-LK", "Tamil (Sri Lanka)", "தமிழ் (இலங்கை)", false),
    ("ta-MY", "Tamil (Malaysia)", "தமிழ் (மலேசியா)", false),
    ("ta-SG", "Tamil (Singapore)", "தமிழ் (சிங்கப்பூர்)", false),
    ("te", "Telugu", "తెలుగు", false),
    ("te-IN", "Telugu (India)", "తెలుగు (భారతదేశం)", false),
    ("mr", "Marathi", "मराठी", false),
    ("mr-IN", "Marathi (India)", "मराठी (भारत)", false),
    ("gu", "Gujarati", "ગુજરાતી", false),
    ("gu-IN", "Gujarati (India)", "ગુજરાતી (ભારત)", false),
    ("kn", "Kannada", "ಕನ್ನಡ", false),
    ("kn-IN", "Kannada (India)", "ಕನ್ನಡ (ಭಾರತ)", false),
    ("ml", "Malayalam", "മലയാളം", false),
    ("ml-IN", "Malayalam (India)", "മലയാളം (ഇന്ത്യ)", false),
    ("pa", "Punjabi", "ਪੰਜਾਬੀ", false),
    ("pa-IN", "Punjabi (India)", "ਪੰਜਾਬੀ (ਭਾਰਤ)", false),
    ("pa-PK", "Punjabi (Pakistan)", "پنجابی (پاکستان)", false),
    ("or", "Odia", "ଓଡ଼ିଆ", false),
    ("or-IN", "Odia (India)", "ଓଡ଼ିଆ (ଭାରତ)", false),
    ("as", "Assamese", "অসমীয়া", false),
    ("as-IN", "Assamese (India)", "অসমীয়া (ভাৰত)", false),
    ("ne", "Nepali", "नेपाली", false),
    ("ne-NP", "Nepali (Nepal)", "नेपाली (नेपाल)", false),
    ("ne-IN", "Nepali (India)", "नेपाली (भारत)", false),
    ("my", "Burmese", "မြန်မာဘာသာ", false),
    ("my-MM", "Burmese (Myanmar)", "မြန်မာဘာသာ (မြန်မာ)", false),
    ("km", "Khmer", "ខ្មែរ", false),
    ("km-KH", "Khmer (Cambodia)", "ខ្មែរ (កម្ពុជា)", false),
    ("lo", "Lao", "ລາວ", false),
    ("lo-LA", "Lao (Laos)", "ລາວ (ລາວ)", false),
    ("mn", "Mongolian", "Монгол", false),
    ("mn-MN", "Mongolian (Mongolia)", "Монгол (Монгол)", false),
    ("kk", "Kazakh", "Қазақ", false),
    ("kk-KZ", "Kazakh (Kazakhstan)", "Қазақ (Қазақстан)", false),
    ("uz", "Uzbek", "Oʻzbek", false),
    ("uz-UZ", "Uzbek (Uzbekistan)", "Oʻzbek (Oʻzbekiston)", false),
    ("ky", "Kyrgyz", "Кыргыз", false),
    ("ky-KG", "Kyrgyz (Kyrgyzstan)", "Кыргыз (Кыргызстан)", false),
    ("tg", "Tajik", "Тоҷикӣ", false),
    ("tj-TJ", "Tajik (Tajikistan)", "Тоҷикӣ (Тоҷикистон)", false),
    ("tk", "Turkmen", "Türkmen", false),
    (
        "tk-TM",
        "Turkmen (Turkmenistan)",
        "Türkmen (Türkmenistan)",
        false,
    ),
    ("az", "Azerbaijani", "Azərbaycan", false),
    (
        "az-AZ",
        "Azerbaijani (Azerbaijan)",
        "Azərbaycan (Azərbaycan)",
        false,
    ),
    ("ka", "Georgian", "ქართული", false),
    ("ka-GE", "Georgian (Georgia)", "ქართული (საქართველო)", false),
    ("hy", "Armenian", "Հայերեն", false),
    ("hy-AM", "Armenian (Armenia)", "Հայերեն (Հայաստան)", false),
    ("ku", "Kurdish", "Kurdî", false),
    ("ku-IQ", "Kurdish (Iraq)", "Kurdî (عێراق)", false),
    ("ku-TR", "Kurdish (Turkey)", "Kurdî (Türkiye)", false),
    ("ku-SY", "Kurdish (Syria)", "Kurdî (Sûriya)", false),
    ("ku-IR", "Kurdish (Iran)", "Kurdî (Îran)", false),
    ("ps", "Pashto", "پښتو", true),
    ("ps-AF", "Pashto (Afghanistan)", "پښتو (افغانستان)", true),
    ("ps-PK", "Pashto (Pakistan)", "پښتو (پاکستان)", true),
    ("sd", "Sindhi", "سنڌي", true),
    ("sd-PK", "Sindhi (Pakistan)", "سنڌي (پاکستان)", true),
    ("sd-IN", "Sindhi (India)", "सिंधी (भारत)", false),
    ("la", "Latin", "Lingua Latina", false),
    (
        "la-VA",
        "Latin (Vatican)",
        "Lingua Latina (Vaticana)",
        false,
    ),
    ("eo", "Esperanto", "Esperanto", false),
    ("eo-001", "Esperanto (World)", "Esperanto (Mondo)", false),
];

pub struct LocalizationEngine {
    pub current_lang: String,
    pub loaded_packs: HashMap<String, LanguagePack>,
}

impl Default for LocalizationEngine {
    fn default() -> Self {
        Self::new()
    }
}

impl LocalizationEngine {
    pub fn new() -> Self {
        let mut loaded = HashMap::new();
        // Load English by default
        loaded.insert(
            "en".to_string(),
            LanguagePack {
                code: "en".to_string(),
                name: "English".to_string(),
                native_name: "English".to_string(),
                rtl: false,
                strings: HashMap::new(), // In production, this would load from a JSON file
            },
        );

        LocalizationEngine {
            current_lang: "en".to_string(),
            loaded_packs: loaded,
        }
    }

    pub fn list_available(&self) -> Vec<(&'static str, &'static str, &'static str, bool)> {
        DEFAULT_LANGUAGES.to_vec()
    }

    pub async fn download_pack(&mut self, code: &str) -> Result<(), String> {
        // Mocking P2P download logic
        tokio::time::sleep(std::time::Duration::from_millis(800)).await;

        let entry = DEFAULT_LANGUAGES
            .iter()
            .find(|(c, _, _, _)| *c == code)
            .ok_or_else(|| format!("Language {} not found", code))?;

        self.loaded_packs.insert(
            code.to_string(),
            LanguagePack {
                code: code.to_string(),
                name: entry.1.to_string(),
                native_name: entry.2.to_string(),
                rtl: entry.3,
                strings: HashMap::new(),
            },
        );

        Ok(())
    }

    pub fn set_language(&mut self, code: &str) -> Result<(), String> {
        if self.loaded_packs.contains_key(code) {
            self.current_lang = code.to_string();
            Ok(())
        } else {
            Err("Language pack not loaded".to_string())
        }
    }
}
