pub mod config;
pub mod crypto;
pub mod data;
pub mod database;
pub mod identity;
pub mod mesh;
pub mod net_share;
pub mod network;
pub mod networking;
pub mod node;
pub mod p2p;
pub mod permissions;
pub mod settings;
pub mod telemetry;
pub mod validation;
pub mod vault;

// Phase 4
pub mod distributed;
// Phase 5
pub mod messaging;
// Phase 6
pub mod marketplace;
// Phase 7
pub mod payment;
// Phase 8
pub mod reputation;
// Phase 9
pub mod social;
// Phase 10
pub mod wager;
// Phase 11
pub mod ai;
// Phase 12
pub mod routing;
// Phase 13
pub mod infrastructure;
// Phase 14
pub mod security;
// Phase 15
pub mod admin;
pub mod commands;
pub mod ecosystem;
pub mod games;
